repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: template.yaml
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.58.4 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: template.yaml
        exclude: .pre-commit-config.yaml
  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args:
          - "--max-line-length=130"
